---

- name: install
  apt: pkg={{ item }}
  with_items:
    # package manager
    - synaptic
    # top-down terminal
    - guake
    # better shell
    - zsh
    # terminal multiplexer
    - tmux
    # terminal editor
    - vim-gtk
    # shh
    - ssh
    # openssl toolkit
    - openssl
    # command line url transfers
    - curl
    # desktop notification library
    - libnotify-bin

    # python package manager
    - python-pip
    # python qt4 required by electrum
    - python-qt4

    # ruby
    - ruby
    # ruby dev headers
    - ruby-dev

    # nodejs
    - nodejs-legacy
    # node package manager
    - npm

# make sure home folder has executable permission so that nginx can run stuff from it
- name: home folder permission
  file: path=/home/{{ user }} mode="701"

- name: setup swappiness
  template: src=swappiness.conf.j2 dest=/etc/sysctl.d/20-swappiness.conf
