- name: passenger ppa key
  apt_key: id=AC40B2F7 state=present url="http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x561F9B9CAC40B2F7"

- name: passenger ppa
  apt_repository: "repo='deb https://oss-binaries.phusionpassenger.com/apt/passenger {{ codename.stdout }} main'"

- name: passenger install
  apt: pkg={{ item }}
  with_items:
    # nginx web server
    - nginx-extras
    # nginx passenger ruby module
    - passenger

- name: passenger nginx config
  template: src=nginx.j2 dest=/etc/nginx/nginx.conf
