- name: postgres ppa key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc

- name: postgres ppa
  apt_repository: "repo='deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main'"

- name: postgres install
  apt: pkg={{ item }}
  with_items:
    # postgres database
    - postgresql-9.3
    # postgres extensions
    - postgresql-contrib-9.3
    # postgres driver lib
    - libpq-dev
    # postgres gui
    - pgadmin3
    # ansible postgres integration
    - python-psycopg2

- name: postgres user
  postgresql_user: name={{ user }} password={{ user }} role_attr_flags=SUPERUSER
  sudo_user: postgres

- name: postgres encoding facts
  shell: "psql -c \"SELECT datname FROM pg_database WHERE encoding = pg_char_to_encoding('UTF8') AND datcollate = 'en_US.utf8' AND datctype = 'en_US.utf8'\""
  sudo_user: postgres
  register: postgres_encoding
  changed_when: False

- name: postgres encoding
  when: "postgres_encoding.stdout.find('template1') == -1"
  shell: "psql -c \"UPDATE pg_database SET encoding = pg_char_to_encoding('UTF8'), datcollate = 'en_US.utf8', datctype = 'en_US.utf8' WHERE datname = 'template1';\""
  sudo_user: postgres
